package com.kb.c_s_system.bean;

public class Coach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.coachId
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer coachid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.name
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.age
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.gender
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.phoneNumber
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.password
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.level
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.reserve
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String reserve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.reserve2
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String reserve2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.coachId
     *
     * @return the value of coach.coachId
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getCoachid() {
        return coachid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.coachId
     *
     * @param coachid the value for coach.coachId
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setCoachid(Integer coachid) {
        this.coachid = coachid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.name
     *
     * @return the value of coach.name
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.name
     *
     * @param name the value for coach.name
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.age
     *
     * @return the value of coach.age
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.age
     *
     * @param age the value for coach.age
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.gender
     *
     * @return the value of coach.gender
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.gender
     *
     * @param gender the value for coach.gender
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.phoneNumber
     *
     * @return the value of coach.phoneNumber
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.phoneNumber
     *
     * @param phonenumber the value for coach.phoneNumber
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setPhonenumber(Integer phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.password
     *
     * @return the value of coach.password
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.password
     *
     * @param password the value for coach.password
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.level
     *
     * @return the value of coach.level
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.level
     *
     * @param level the value for coach.level
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.reserve
     *
     * @return the value of coach.reserve
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.reserve
     *
     * @param reserve the value for coach.reserve
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.reserve2
     *
     * @return the value of coach.reserve2
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.reserve2
     *
     * @param reserve2 the value for coach.reserve2
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }
}