package com.kb.c_s_system.bean;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseId
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseName
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.startTime
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8" )
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.endTime
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8" )
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.coachId
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    private Integer coachid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.reserve
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    private String reserve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.num_limit
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    private Integer numLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseId
     *
     * @return the value of course.courseId
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseId
     *
     * @param courseid the value for course.courseId
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.startTime
     *
     * @return the value of course.startTime
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.startTime
     *
     * @param starttime the value for course.startTime
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.endTime
     *
     * @return the value of course.endTime
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.endTime
     *
     * @param endtime the value for course.endTime
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.coachId
     *
     * @return the value of course.coachId
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public Integer getCoachid() {
        return coachid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.coachId
     *
     * @param coachid the value for course.coachId
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public void setCoachid(Integer coachid) {
        this.coachid = coachid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.reserve
     *
     * @return the value of course.reserve
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.reserve
     *
     * @param reserve the value for course.reserve
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.num_limit
     *
     * @return the value of course.num_limit
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public Integer getNumLimit() {
        return numLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.num_limit
     *
     * @param numLimit the value for course.num_limit
     *
     * @mbg.generated Thu Dec 12 16:31:23 CST 2019
     */
    public void setNumLimit(Integer numLimit) {
        this.numLimit = numLimit;
    }

    @Override
    public String toString() {
        return "Course{" +
                "courseid=" + courseid +
                ", coursename='" + coursename + '\'' +
                ", starttime=" + starttime +
                ", endtime=" + endtime +
                ", coachid=" + coachid +
                ", reserve='" + reserve + '\'' +
                ", numLimit=" + numLimit +
                '}';
    }
}