package com.kb.c_s_system.bean;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.cardId
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer cardid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.age
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phoneNumber
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.startDate
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8" )
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.expiryDate
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8" )
    private Date expirydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.level
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.reserve
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String reserve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.reserve2
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    private String reserve2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.cardId
     *
     * @return the value of member.cardId
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.cardId
     *
     * @param cardid the value for member.cardId
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.age
     *
     * @return the value of member.age
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.age
     *
     * @param age the value for member.age
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phoneNumber
     *
     * @return the value of member.phoneNumber
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phoneNumber
     *
     * @param phonenumber the value for member.phoneNumber
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setPhonenumber(Integer phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.startDate
     *
     * @return the value of member.startDate
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.startDate
     *
     * @param startdate the value for member.startDate
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.expiryDate
     *
     * @return the value of member.expiryDate
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Date getExpirydate() {
        return expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.expiryDate
     *
     * @param expirydate the value for member.expiryDate
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.level
     *
     * @return the value of member.level
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.level
     *
     * @param level the value for member.level
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.reserve
     *
     * @return the value of member.reserve
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.reserve
     *
     * @param reserve the value for member.reserve
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.reserve2
     *
     * @return the value of member.reserve2
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.reserve2
     *
     * @param reserve2 the value for member.reserve2
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }
}