package com.kb.c_s_system.dao;

import com.kb.c_s_system.bean.Coach;
import com.kb.c_s_system.bean.CoachExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    long countByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int deleteByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int deleteByPrimaryKey(Integer coachid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int insert(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int insertSelective(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    List<Coach> selectByExample(CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    Coach selectByPrimaryKey(Integer coachid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") Coach record, @Param("example") CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByExample(@Param("record") Coach record, @Param("example") CoachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByPrimaryKeySelective(Coach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coach
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByPrimaryKey(Coach record);
}