package com.kb.c_s_system.dao;

import com.kb.c_s_system.bean.Member_course;
import com.kb.c_s_system.bean.Member_courseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Member_courseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    long countByExample(Member_courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int deleteByExample(Member_courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int insert(Member_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int insertSelective(Member_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    List<Member_course> selectByExample(Member_courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    Member_course selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") Member_course record, @Param("example") Member_courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByExample(@Param("record") Member_course record, @Param("example") Member_courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByPrimaryKeySelective(Member_course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_course
     *
     * @mbg.generated Fri Nov 15 14:35:01 CST 2019
     */
    int updateByPrimaryKey(Member_course record);
}